using AI.Solutions.Application.Interfaces;

namespace AI.Solutions.Infrastructure.Services;

/// <summary>
/// Mock AI service that generates simulated responses.
/// Designed to be easily replaced with OpenAI or other LLM APIs.
/// </summary>
public class AiMockService : IAiService
{
    private static readonly string[] Greetings = {
        "Based on your data, here's what I found:",
        "Great question! Let me analyze that for you:",
        "Here's my analysis based on the available information:"
    };

    private static readonly string[] Responses = {
        "The trends show a positive trajectory with a 15% increase over the last quarter. Key factors include improved user engagement and higher conversion rates across all channels.",
        "After analyzing the data, I recommend focusing on three key areas: customer retention (currently at 87%), new market expansion, and optimizing your API integration pipeline.",
        "Your current metrics look strong. Total revenue is up 12% month-over-month, with the highest growth in the enterprise segment. I'd suggest reviewing the pricing strategy for the Pro tier.",
        "The performance analysis indicates that response times have improved by 23% since the last optimization. Database queries are averaging 45ms, well within the target threshold.",
        "Based on the pattern analysis, I've identified several opportunities for automation that could save approximately 15 hours per week across your team's workflows."
    };

    public Task<string> GenerateResponseAsync(string userMessage, CancellationToken ct = default)
    {
        var rng = new Random();
        var greeting = Greetings[rng.Next(Greetings.Length)];
        var response = Responses[rng.Next(Responses.Length)];
        return Task.FromResult($"{greeting}\n\n{response}");
    }

    public Task<string> GenerateReportAsync(string reportTitle, CancellationToken ct = default)
    {
        var report = $"""
        # {reportTitle}
        
        ## Executive Summary
        This AI-generated report provides a comprehensive analysis of the requested topic. Key findings indicate positive trends across all measured metrics.
        
        ## Key Metrics
        - User Growth: +18% month-over-month
        - Revenue: $142,500 (up from $120,800)
        - API Requests: 1.2M total this period
        - Customer Satisfaction: 4.7/5.0
        
        ## Recommendations
        1. Scale infrastructure to handle projected 25% traffic increase
        2. Implement advanced caching for frequently accessed endpoints
        3. Expand the AI training dataset for improved accuracy
        
        ## Conclusion
        The overall trajectory is positive. Continue monitoring key KPIs and adjust strategy based on quarterly reviews.
        
        *Report generated by AI Solutions on {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC*
        """;
        return Task.FromResult(report);
    }
}
